[project]
name = "nx-workers"
version = "0.0.0"
dependencies = [
    "scapy",
    "redis",
]

[project.optional-dependencies]
dev = [
    "flake8",
    "pytest",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
