[project]
name = "nx-workers"
dependencies = [
    "scapy",
    "redis",
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "flake8",
    "pytest",
]

[project.scripts]
carla = "nx.workers.carla:main"
daniel = "nx.workers.daniel:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = {attr = "nx.__version__"}
